### PR TITLE
Do not rely on data.errored

### PR DESCRIPTION
**Pull request by subzey**
Stylelint doesn't set `"errored": true` in the JSON if there were only warnings, but no errors.
It leads to the wrong behavior when warnings are not shown at all on a file without errors.

_This results somewhat funny outcome: I had to add errors intentionally to make warnings visible._

### CODE REVIEW

**Comment by subzey** [comment]
_Uh... Looks like @nwoltman was the first to send the similar PR (#45)_

**Comment by nwoltman** [comment]
@kungfusheep \*ping\*

**Comment by leptest** [comment]
This has helped me a lot!
Any chance we can get it merge in?

Thanks,
Daniel

**Comment by kungfusheep** [comment]
Merged - sorry for the delay.

**Comment by leptest** [comment]
Thanks @kungfusheep and @subzey! :D

**Comment by subzey** [comment]
@kungfusheep Thank you! 🎆

**Pull request merged**
