### PR TITLE
Nodelinter

### PR DESCRIPTION
**Pull request by flops**
Now it works with stylelint cli wthout inner js wrappers, and errors parsing from `--format json` export.

Cons:
- Removed old client support 

Pros:
- Works as is
- Cli is detecting syntaxt itself
- Configuration of project now can be more various like in stylelint docs
- Lot of issues like #15, #16, #17, #21, #23, #24, #36 and a few more can be resolved

### CODE REVIEW

**Comment by aziz** [comment]
Why this pull request is not merged, it's way better and does not have current bugs. 
please merge this ASAP

**Comment by tomahl** [comment]
@kungfusheep if you're low on motivation or just can't find the time, please consider help from the community. This package is important for many of us but is unfortunately a bit outdated.

**Comment by kungfusheep** [comment]
@tomahl apologies. Between a huge project at work this year and family life I simply don't have time to check these as often as I have in the past. I don't have time to fully validate your change but it seems sound. If there are any issues I'll try to merge as soon as I can.

**Comment by tomahl** [comment]
@kungfusheep you have nothing to apologize for. Thanks for your great work, and thanks to @flops for the commit. 👍

**Comment by flops** [comment]
@kungfusheep thanks for accepting pull request, i can support this project, cause i using it in my work.
Would be great to clean up old issues, but even if i will bug fix, i don't know how to make it a bit faster.
And i didn't create a version tag for repo, so it would be nice to add 1.1.0 for package control could resolve version correctly.

**Comment by nwoltman** [comment]
@kungfusheep I understand that you are very busy, however, I think many people would appreciate it if you could create a new tag for the repo so that we may access these changes through Package Control.

**Comment by tomahl** [comment]
Yes, please do. I was so happy to see this commit being merged and now I/we can't access it.

**Comment by kungfusheep** [comment]
2.0.0 pushed

**Comment by tomahl** [comment]
@kungfusheep thank you so much! :)

**Pull request merged**
